[package]
name = "ginko"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "A device-tree source parser and analyzer"
repository = "https://github.com/kraigher/rust_hdl"
authors = ["Lukas Scheller <lukasscheller@icloud.com>"]

[dependencies]
assert_unordered = "0.3.5"
clap = { version = "4.4.16", features = ["derive"] }
colored = "2.1.0"
itertools = "0.12.0"
url = "2.5.0"
